name: HCA Details
on:
  workflow_dispatch:

jobs:
  start-vps:
    runs-on: ubuntu-latest

    steps:
    - name: print version
      run: |
        sudo su
        ls -la /opt/hca
        cat /opt/hca/.settings
        
